### ISSUE TITLE
感谢大神的付出与分享！弱弱的问下：如何开启BBR加速？

### ISSUE THREAD

**Issue by BetterLuke** [LewiVir/NanoPi-R4S#11]
RT: 感谢大神的付出与分享！弱弱的问下：如何开启BBR加速？

**Comment by LewiVir** [comment]
经测试，flowoffload插件（也即Turbo Acc加速)在当前固件中运行会导致无法联网，因此取消了该插件的集成，BBR的选项也包含在这个插件中。

**Comment by BetterLuke** [comment]
> 经测试，flowoffload插件（也即Turbo Acc加速)在当前固件中运行会导致无法联网，因此取消了该插件的集成，BBR的选项也包含在这个插件中。

了解，期待生态越来越好，昨天我已安装上！
