### ISSUE TITLE
firstboot & ssrp & hello world notwork

### ISSUE THREAD

**Issue by galaxyskyknight** [LewiVir/NanoPi-R4S#12]
issue1: flash the latest version, do nothing and go direlty to tty terminal via web, type 'firstboot' it promtps the mtd rootfs_data partition not found, and cannot restore to factory configuration.
issue2: ssrp and hello world cannot change to running status after add a v2ray node. it says the ssr tcp redirect error or some problems there.

Please help to check. and on the otherhand,  why this image makes so many scattered partitions( ~4M each) there? it seems so strange.

**Comment by LewiVir** [comment]
Issue 1: Does this issue affect any functionality?

Issue 2: It was reportedly that versions before 20201204v2 (including) had no troubles with v2ray. Therefore, I compared that commit to the latest one, and it seemed that changes to the configuration had no direct linkage to this issue. I would attribute this to the changes of upstream codes, and will trigger another build to see if it still exists.

Scattered Partitions: $ parted FriendlyWrt_20201209_NanoPi-R4S_arm64_sd.img 

GNU Parted 3.3
Using ~/FriendlyWrt_20201209_NanoPi-R4S_arm64_sd.img
Welcome to GNU Parted! Type 'help' to view a list of commands.
(parted) p                                                                
Model:  (file)
Disk ~/FriendlyWrt_20201209_NanoPi-R4S_arm64_sd.img: 2000MB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name      Flags
 1      8389kB  12.6MB  4194kB               uboot
 2      12.6MB  16.8MB  4194kB               trust
 3      16.8MB  21.0MB  4194kB               misc
 4      21.0MB  25.2MB  4194kB               dtbo
 5      25.2MB  41.9MB  16.8MB               resource
 6      41.9MB  83.9MB  41.9MB               kernel
 7      83.9MB  134MB   50.3MB               boot
 8      134MB   940MB   805MB   ext4         rootfs
 9      940MB   2000MB  1060MB  ext4         userdata

The structure is identical to that of the official firmware.

**Comment by galaxyskyknight** [comment]
OK. for issue 1,not major now. Just that I didn't have a proper way to restore to factory(if you have another way besides this command?) for issue 2, I will try the build you mentioned.  The partitions if you checked align with official, it's fine.

**Comment by galaxyskyknight** [comment]
I flashed 20201202 v2 image, still I got the shadowsocksr service cannot be running after I configured one valid v2ray node,I am wondering if this is related to the 'rootfs_data' partition missing issue? see the snapshot
![20201202version2](https://user-images.githubusercontent.com/66289873/102012774-45735e00-3d87-11eb-822b-8476de76f600.jpg)
![rootfs_data_lost](https://user-images.githubusercontent.com/66289873/102012784-4e642f80-3d87-11eb-9573-586a0d3d6ca2.jpg)
![v2ray](https://user-images.githubusercontent.com/66289873/102012793-57550100-3d87-11eb-8a23-aae763c1e4f9.jpg)

**Comment by LewiVir** [comment]
最新的OpenWrt固件已解决
