### ISSUE TITLE
 感谢编译R4S固件

### ISSUE THREAD

**Issue by Leon11111111** [LewiVir/NanoPi-R4S#13]
R4S固件真的好稀少好难找，希望大佬再接再厉，完善固件，再次感谢！！！

**Comment by galaxyskyknight** [comment]
同感谢，希望不要停啊。我们买了这货，不希望成为某些嘴炮和Up主的6元牺牲品，还请大佬们多支持。

**Comment by fly127** [comment]
感谢编译，期待继续完善

**Comment by spypie** [comment]
感谢，已经借鉴了这位大神的代码，本地编译成功了，谢谢
