### ISSUE TITLE
20201217 Lean OpenWrt 堪称GDQ 谢谢LewiVir

### ISSUE THREAD

**Issue by bg4drl** [LewiVir/NanoPi-R4S#17]
20201217 Lean OpenWrt 堪称GDQ 谢谢LewiVir
试了走主路由和网关路由都非常的优秀 跑满怠速

**Comment by bitest** [comment]
请问你是怎么刷的1217版啊，我不知道怎么升级sysupgrade版的img

**Comment by Freelement** [comment]
> 请问你是怎么刷的1217版啊，我不知道怎么升级sysupgrade版的img

我直接删了旧分区刷进去，就当sysupgrade这个词不存在

**Comment by LewiVir** [comment]
sysupgrade指固件本身支持在线升级，但首次需要全新刷入，因为配置文件可能经常变动，因此后面也不建议在线升级

**Comment by bitest** [comment]
> sysupgrade指固件本身支持在线升级，但首次需要全新刷入，因为配置文件可能经常变动，因此后面也不建议在线升级

我还是没法成功使用，我用Etcher刷写1217的固件到sd卡只有两个分区，没法启动。
![屏幕截图 2020-12-18 120651](https://user-images.githubusercontent.com/20890141/102573597-bf11a000-4129-11eb-8130-dbbf3ccdbb85.png)

**Comment by LewiVir** [comment]
你的是4G版本吗

**Comment by bitest** [comment]
1G版本，刷1209没问题。

**Comment by LewiVir** [comment]
> > 你的是4G版本吗
> 
> 1G版本，刷1209没问题，sd卡有9个分区

现在固件只支持4G版，今天我会添加1G的支持

**Comment by bitest** [comment]
原来如此，谢谢大佬。

**Comment by bg4drl** [comment]
> > > 你的是4G版本吗
> > 
> > 
> > 1G版本，刷1209没问题，sd卡有9个分区
> 
> 现在固件只支持4G版，今天我会添加1G的支持

WAN/LAN口对换的，昨天发现MAC地址重启就变 ，config加option没什么效果
请问固件端有没有更好的办法... Windows连接名每次就增分上去了

**Comment by bg4drl** [comment]
另外一点 “重启” 后 还是要拔电才能启动 红灯亮着走不到uboot

**Comment by LewiVir** [comment]
> > > > 你的是4G版本吗
> > > 
> > > 
> > > 1G版本，刷1209没问题，sd卡有9个分区
> > 
> > 
> > 现在固件只支持4G版，今天我会添加1G的支持
> 
> WAN/LAN口对换的，昨天发现MAC地址重启就变 ，config加option没什么效果
> 请问固件端有没有更好的办法... Windows连接名每次就增分上去了

不太明白 WAN/LAN口对换 是什么意思？MAC地址应该是不变的，固件也没必要伪造MAC吧。

**Comment by LewiVir** [comment]
> 另外一点 “重启” 后 还是要拔电才能启动 红灯亮着走不到uboot

这个情况我只遇到一次。原因未知，也是我的能力范围之外了。
