### ISSUE TITLE
感谢大佬制作固件

### ISSUE THREAD

**Issue by wifiway520** [LewiVir/NanoPi-R4S#18]
感谢大佬制作固件，有没有红包二维码，让大佬有动力持续更新！

**Comment by LewiVir** [comment]
还是不收钱了吧，收了我就提前变成打工人了😎

**Comment by bg4drl** [comment]
咖啡链接可以码 哈哈哈

LewiVir <notifications@github.com> 于2020年12月18日周五 下午12:32写道：

**Comment by wifiway520** [comment]
&nbsp; &nbsp; &nbsp;红包而已，纯属个人行为，即便你不再更新，也只是个红包，就像其他好的项目譬如ventoy,我就捐过几次，也想加入测试，虽然不多也没吊我,😂😂。我也只会基础编译，看了有你编译r4s,我才买的.所以希望你坚持，arm固件很少，也希望有人像lean大拿一样，开发个项目就可以盆满钵满，到时候也是你应得的！
&nbsp; &nbsp; &nbsp;扯远了，三天后机器到，我会测试，提交bug别嫌烦哈😁😁😁！！



---原始邮件---
发件人: "LewiVir"<notifications@github.com&gt;
发送时间: 2020年12月18日(周五) 中午12:32
收件人: "LewiVir/NanoPi-R4S"<NanoPi-R4S@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"wifiway520"<wifiway@qq.com&gt;;
主题: Re: [LewiVir/NanoPi-R4S] 感谢大佬制作固件 (#18)




 
还是不收钱了吧，收了我就提前变成打工人了😎
