### ISSUE TITLE
大佬，18号的固件IP换回来了吗？

### ISSUE THREAD

**Issue by MedyMa** [LewiVir/NanoPi-R4S#19]

**Comment by LewiVir** [comment]
还没有，不知道为什么添加的配置失效了，还是.1.1

**Comment by MedyMa** [comment]
卧槽，早上4点半试了一次，结果发现没有改回来，然就去睡觉去了

**Comment by Leon11111111** [comment]
进去自己改一下不行吗。。。

> 卧槽，早上4点半试了一次，结果发现没有改回来，然就去睡觉去了

进去自己改一下不行吗。。。

**Comment by MedyMa** [comment]
改了之后你会发现概况里啥都没了

**Comment by MedyMa** [comment]
> 进去自己改一下不行吗。。。
> 
> > 卧槽，早上4点半试了一次，结果发现没有改回来，然就去睡觉去了
> 
> 进去自己改一下不行吗。。。

改完之后，你会发现概况里啥都没了

**Comment by LewiVir** [comment]
对，的确有这个问题，暂时没法改，我看下怎么解决

**Comment by Leon11111111** [comment]
> > 进去自己改一下不行吗。。。
> > > 卧槽，早上4点半试了一次，结果发现没有改回来，然就去睡觉去了
> > 
> > 
> > 进去自己改一下不行吗。。。
> 
> 改完之后，你会发现轮廓里啥都没了

那么夸张。。。我还没刷，但是以前刷过1.1的改了还是正常的呀

**Comment by LewiVir** [comment]
亲测更改为2.1会有问题，3.1和10.1都没有问题。若更改为2.1导致无法进入管理界面，参考 https://mlapp.cn/1008.html 在命令行中修改LAN IP地址。

**Comment by Leon11111111** [comment]
> 亲测更改为2.1会有问题，3.1和10.1都没有问题。若更改为2.1导致无法进入管理界面，参考https://mlapp.cn/1008.html在命令行中修改LAN IP地址。

收到，晚上回家试试，谢谢

**Comment by bg4drl** [comment]
> > 亲测更改为2.1会有问题，3.1和10.1都没有问题。若更改为2.1导致无法进入管理界面，参考[https://mlapp.cn/1008.html在命令行中修改LAN](https://mlapp.cn/1008.html%E5%9C%A8%E5%91%BD%E4%BB%A4%E8%A1%8C%E4%B8%AD%E4%BF%AE%E6%94%B9LAN) IP地址。
> 
> 收到，晚上回家试试，谢谢

先走通主路由模式后改旁路有有效 直接改会找不到eth
LewiVir大大的指南很管用

**Comment by bigdongdongCLUB** [comment]
改成原来的IP 入2.1有问题 是因为浏览器有旧缓存。清理一下浏览器cookie就好了

> 亲测更改为2.1会有问题，3.1和10.1都没有问题。若更改为2.1导致无法进入管理界面，参考 https://mlapp.cn/1008.html 在命令行中修改LAN IP地址。

**Comment by LewiVir** [comment]
> 改成原来的IP 如2.1有问题 是因为浏览器有旧缓存。清理一下浏览器cookie就好了
> 
> > 亲测更改为2.1会有问题，3.1和10.1都没有问题。若更改为2.1导致无法进入管理界面，参考 https://mlapp.cn/1008.html 在命令行中修改LAN IP地址。

确实是浏览器Cookie的问题。
