### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by helaobibi** [LewiVir/NanoPi-R4S#2]
大佬你咋编译的啊，我自己弄了一个ubuntu18.04，环境都弄好，L大源码和官方的源码融合不加任何科学上网模块正常编译，加了以后就编译错误，upx ucl都加了，折腾2-3天了，一直编译失败，求大佬看看

**Comment by LewiVir** [comment]
请参考 workflow 中 Merge LEDE 到 Update Feeds，看是否是缺了某些步骤
