### ISSUE TITLE
Netdata版本很旧 20200416-521-g543a4a41a 

### ISSUE THREAD

**Issue by bg4drl** [LewiVir/NanoPi-R4S#22]
如果是汉化没办法,只有4月份版本,麻烦调升下: v1.27.0 谢谢

**Comment by LewiVir** [comment]
我目前和原作者保持同步。他用的是比较老的luci库，可能是为了稳定性，后面会尝试新的版本。

**Comment by bg4drl** [comment]
谢谢 LewiVir大大
尝鲜的代价还是很高的 
这点R2S太稳 , 稳的有点没有了刺激.
 x86更是 简直会是变刷卡的小电工 
(养老版名称很有趣)
