### ISSUE TITLE
2020-12-17 Lean OpenWrt 版本无法正常重启

### ISSUE THREAD

**Issue by hetao8980823** [LewiVir/NanoPi-R4S#24]
正常重启之后只有电源指示灯亮起。其他都不亮系统无法正常启动。重新插拔电源之后正常，试了很多次都这样

**Comment by LewiVir** [comment]
请等待稍后更新的版本，看是否能解决该问题

**Comment by galaxyskyknight** [comment]
一样，4G版本根本无法启动系统

**Comment by LewiVir** [comment]
> 一样，4G版本根本无法启动系统

刷入的文件是哪个？无法启动系统的具体表现是什么？我的ext4版本运行正常，重启没有问题。

**Comment by galaxyskyknight** [comment]
ext4没问题，squashfs的不行，包括刚才18号的版本

**Comment by LewiVir** [comment]
亲测4G Lean版本squashfs可以启动和正常重启

**Comment by galaxyskyknight** [comment]
那就怪了，我的squashfs 用的64G卡，sys灯不亮，换16G卡，sys灯常亮，但是lan起不来。刷ext4的版本就没问题了。

**Comment by LewiVir** [comment]
检查下是不是下载导致文件损坏。我也是用64G卡测试。

**Comment by galaxyskyknight** [comment]
另外还有好多小毛病，不知道是固件还是插件的问题 1）ssrp 里面->状态->GFW那几个列表更新不了。2) PASSWALL里面->运行状态->百度链接，毫秒数都是错的，点google链接测试也不通，但实际是代理上了的 3）mwan3能不能加上？自己安装包里搜说有几个包在库里没有，不敢乱填库链接 4）shell能否不用busybox? 我不知道怎么控制需要输入密码才能ssh, 不想用密钥形式，大佬教教？

**Comment by LewiVir** [comment]
> 另外还有好多小毛病，不知道是固件还是插件的问题 1）ssrp 里面->状态->GFW那几个列表更新不了。2) PASSWALL里面->运行状态->百度链接，毫秒数都是错的，点google链接测试也不通，但实际是代理上了的 3）mwan3能不能加上？自己安装包里搜说有几个包在库里没有，不敢乱填库链接 4）shell能否不用busybox? 我不知道怎么控制需要输入密码才能ssh, 不想用密钥形式，大佬教教？

亲测ssrp列表可以更新，百度链接速度正常，google连接可以ping通。ssh仅仅是shell更换为zsh，其他和原来一样。

**Comment by LewiVir** [comment]
我建议首先检查固件下载没有问题，其次检查节点状态和网络连接状态正常。

**Comment by galaxyskyknight** [comment]
![屏幕截图 2020-12-19 003210](https://user-images.githubusercontent.com/66289873/102637956-beacef80-4191-11eb-91df-45880494206a.jpg)

**Comment by LewiVir** [comment]
我的是SSR节点，可能问题来自于Xray。

**Comment by galaxyskyknight** [comment]
谷歌油管都能开，ip111.cn显示国内国外都正常，就是谷歌链接和github链接这里测试失败，百度链接ms数错到天上....google的节点检查那个也是显示OK的（截图没点所以无测试结果）

**Comment by LewiVir** [comment]
毕竟不是稳定版本，等待上游修复。

**Comment by hetao8980823** [comment]
补充一下我用的squashfs的固件还没试过ext4版本，机器是4g 内存的，另外内存卡是闪迪的和三星卡都试过，还有个小建议麻烦编译个磁盘管理插件方便对剩余内存卡空间进行分区。网络接口vpn 接口有显示错误。

**Comment by galaxyskyknight** [comment]
> 毕竟不是稳定版本，等待上游修复。

好的，感谢大佬

**Comment by galaxyskyknight** [comment]
> 补充一下我用的squashfs的固件还没试过ext4版本，机器是4g 内存的，另外内存卡是闪迪的和三星卡都试过，还有个小建议麻烦编译个磁盘管理插件方便对剩余内存卡空间进行分区。网络接口vpn 接口有显示错误。

系统->磁盘管理.....

**Comment by LewiVir** [comment]
> 补充一下我用的squashfs的固件还没试过ext4版本，机器是4g 内存的，另外内存卡是闪迪的和三星卡都试过，还有个小建议麻烦编译个磁盘管理插件方便对剩余内存卡空间进行分区。网络接口vpn 接口有显示错误。

参考README中的说明进行扩容。我也是4G版本，squashfs和ext4在我这里都正常，闪迪卡。VPN这个不知道是不是因为没配置时显示成这样。

**Comment by hetao8980823** [comment]
好的，谢谢大佬
