### ISSUE TITLE
提交一个1209固件的小问题

### ISSUE THREAD

**Issue by alicechino** [LewiVir/NanoPi-R4S#25]
端口转发貌似完全就是废的，我转发了NAS管理页面的端口之后用公网ip+转发之后的端口完全无法访问NAS的管理页面..我自己是独立的公网IP的..而且如果设置转发5000端口的话，会直接导致系统崩溃，必须强制重启。。顺便问一下大佬啥时候lean的op可以给1GB用orz..

**Comment by alicechino** [comment]
还有就是ipv6上虽然能获取到公网的ipv6地址，但是路由下的设备却完全分配不到...lan的设置里面已经开启v6了

**Comment by LewiVir** [comment]
> 端口转发貌似完全就是废的，我转发了NAS管理页面的端口之后用公网ip+转发之后的端口完全无法访问NAS的管理页面..我自己是独立的公网IP的..而且如果设置转发5000端口的话，会直接导致系统崩溃，必须强制重启。。顺便问一下大佬啥时候lean的op可以给1GB用orz..

正在编译中

**Comment by LewiVir** [comment]
> 还有就是ipv6上虽然能获取到公网的ipv6地址，但是路由下的设备却完全分配不到...lan的设置里面已经开启v6了

新版运行正常，更新即可

**Comment by alicechino** [comment]
> > 还有就是ipv6上虽然能获取到公网的ipv6地址，但是路由下的设备却完全分配不到...lan的设置里面已经开启v6了
> 
> 新版运行正常，更新即可

看到了，谢谢大佬，但是我该用哪个呀 一堆rom包。。

**Comment by LewiVir** [comment]
ext4或squashfs，建议用Lean版，快编译好了

**Comment by alicechino** [comment]
> ext4或squashfs，建议用Lean版，快编译好了
squashfs启动不能..ext4版正常启动，但是bug非常多
目前遇到的：上网速度非常非常慢，时断时连，虽然wan的ip一直在连接状态
SSRPLUS+和hello world都无法正常使用 passwall正常
如果没接入互联网，后台的速度慢的令人发指..
1GB版

**Comment by alicechino** [comment]
> ext4或squashfs，建议用Lean版，快编译好了

squashfs启动不能..ext4版正常启动，但是bug非常多
目前遇到的：上网速度非常非常慢，时断时连，虽然wan的ip一直在连接状态
SSRPLUS+和hello world都无法正常使用 passwall正常
如果没接入互联网，后台的速度慢的令人发指..
1GB版

**Comment by LewiVir** [comment]
> > ext4或squashfs，建议用Lean版，快编译好了
> 
> squashfs启动不能..ext4版正常启动，但是bug非常多
> 目前遇到的：上网速度非常非常慢，时断时连，虽然wan的ip一直在连接状态
> SSRPLUS+和hello world都无法正常使用 节点也无法订阅 passwall正常
> 如果没接入互联网，后台的速度慢的令人发指..
> 端口可以正常转发了 1209版不行
> 再就是重启之后系统无法启动，需要断电重新开机..
> 1GB版

Official OpenWrt版存在后台访问慢的问题。无法启动是uboot的问题，无能为力。4G版本重启正常，squasfs正常，ssr和vssr节点订阅正常SSR节点使用正常。

**Comment by LewiVir** [comment]
对于无法启动的问题，某些劣质或低速存储卡可能导致无法启动。

**Comment by alicechino** [comment]
> 对于无法启动的问题，某些劣质或低速存储卡可能导致无法启动。

我是闪迪的至尊极速64GB。读160写60。京东买的，我用的是lean版 可惜4GB版没货 不然我就一步到位了 哭哭

**Comment by LewiVir** [comment]
同款卡，那就是1G版本的uboot存在问题。

**Comment by alicechino** [comment]
> 对于无法启动的问题，某些劣质或低速存储卡可能导致无法启动。

总之谢谢大佬了，看来只能先收起来继续用AX86U了..等以后有完善的固件再拿出来用，其实1209只要能解决端口转发不出去的问题我觉得就是很好的固件了
