### ISSUE TITLE
增加多拨

### ISSUE THREAD

**Issue by fhk579** [LewiVir/NanoPi-R4S#30]
烦请大佬增加多拨插件，或提供可以增加的办法。谢谢

**Comment by LewiVir** [comment]
多播指的是哪款插件？mwan3在Lean版中有集成。可以fork到自己目录下修改配置文件增加插件并编译。

**Comment by fhk579** [comment]
谢谢！
可以集成luci-app-syncdial吗，我安装不上或安装上了不能用。

**Comment by fhk579** [comment]
谢谢！我现在换成Lean版的了。开始用的是Official版，里面没有
