### ISSUE TITLE
Lean、1219的4GB版本无法正常重启

### ISSUE THREAD

**Issue by GeorgeLeungHK** [LewiVir/NanoPi-R4S#31]
该rom尝试在luci点击重启或者使用ssh打命令reboot后，r4s直接关机，也无法重新连接上。需要拔掉电源重新开机。

**Comment by LewiVir** [comment]
很奇怪，我也是4GB版，Lean 1219 ext4，重启了很多次，不管是luci还是ssh，没出现过问题。昨天有人反馈这个问题，1218的两个版本的四套固件我都亲自测了，重启都没有问题。1G版本手上没有，没法测。请确认下下载的镜像没有损坏，可以计算checksum和release的sha256sums中的信息校对。

**Comment by GeorgeLeungHK** [comment]
我试过ext4和squashfs两个版本，都有相同的问题发生。貌似是必现的。而且我做过checksum校对了。

**Comment by LewiVir** [comment]
明天的固件将会尝试修复这个问题

**Comment by cerellean** [comment]
刚测了下手上的1G版本，也存在这个问题。

**Comment by GeorgeLeungHK** [comment]
这是我刚刚在luci点击重启后的log，我的r4s只启用了passwall，其他模块均没有启动。

Sat Dec 19 18:05:38 2020 daemon.err uhttpd[3935]: uci: Entry not found
Sat Dec 19 18:05:38 2020 daemon.err uhttpd[3935]: sh: /etc/init.d/dockerman: line 6: config_load: not found
Sat Dec 19 18:05:38 2020 daemon.err uhttpd[3935]: sh: /etc/init.d/dockerman: line 7: config_get: not found
Sat Dec 19 18:05:39 2020 daemon.err uhttpd[3935]: sh: /etc/init.d/haproxy: line 21: extra_command: not found
Sat Dec 19 18:05:39 2020 daemon.err uhttpd[3935]: /etc/rc.common: /etc/init.d/haproxy: line 21: extra_command: not found
Sat Dec 19 18:05:53 2020 user.info mwan3track[5961]: Check (ping) failed for target "114.114.115.115" on interface wan (eth0)
Sat Dec 19 18:05:59 2020 user.info mwan3track[5961]: Lost 1 ping(s) on interface wan (eth0)
Sat Dec 19 18:06:16 2020 user.info mwan3track[5961]: Check (ping) failed for target "114.114.115.115" on interface wan (eth0)
Sat Dec 19 18:06:18 2020 daemon.info procd: - shutdown -
Sat Dec 19 18:06:18 2020 daemon.notice procd: /etc/rc.d/K01AdGuardHome: awk: /etc/config/AdGuardHome.yaml: No such file or directory
Sat Dec 19 18:06:18 2020 daemon.notice procd: /etc/rc.d/K01AdGuardHome: AdGuardHome service disabled
Sat Dec 19 18:06:18 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:06:18 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:06:18 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:06:18 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:06:18 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:06:18 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:06:18 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:06:19 2020 daemon.notice procd: /etc/rc.d/K10serverchan: serverchan exit ...
Sat Dec 19 18:06:20 2020 cron.err crond[19557]: crond (busybox 1.31.1) started, log level 8
Sat Dec 19 18:06:20 2020 daemon.notice procd: /etc/rc.d/K10xlnetacc: Stop XLNetAcc process PID: 19571
Sat Dec 19 18:06:20 2020 daemon.info udpspeeder[4519]: [0m[32m[2020-12-19 18:06:20][INFO]got sigterm, exit[0m[0m
Sat Dec 19 18:06:20 2020 daemon.info udpspeeder[4518]: [0m[32m[2020-12-19 18:06:20][INFO]got sigterm, exit[0m[0m
Sat Dec 19 18:06:22 2020 user.info mwan3track[5961]: Lost 1 ping(s) on interface wan (eth0)
Sat Dec 19 18:06:22 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sat Dec 19 18:06:22 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sat Dec 19 18:06:26 2020 daemon.info dnsmasq[19932]: Connected to system UBus
Sat Dec 19 18:06:31 2020 cron.err crond[20063]: crond (busybox 1.31.1) started, log level 8
Sat Dec 19 18:06:31 2020 daemon.notice procd: /etc/rc.d/K15openclash: OpenClash Already Stop
Sat Dec 19 18:06:31 2020 cron.err crond[20206]: crond (busybox 1.31.1) started, log level 8
Sat Dec 19 18:06:31 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sat Dec 19 18:06:31 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sat Dec 19 18:06:34 2020 daemon.info dnsmasq[20376]: Connected to system UBus
Sat Dec 19 18:06:35 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sat Dec 19 18:06:35 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sat Dec 19 18:06:39 2020 daemon.info dnsmasq[20584]: Connected to system UBus
Sat Dec 19 18:06:39 2020 cron.err crond[20619]: crond (busybox 1.31.1) started, log level 8
Sat Dec 19 18:06:39 2020 daemon.notice procd: /etc/rc.d/K15vssr: stop
Sat Dec 19 18:06:39 2020 cron.err crond[20788]: crond (busybox 1.31.1) started, log level 8
Sat Dec 19 18:06:39 2020 authpriv.info dropbear[12066]: Early exit: Terminated by signal

**Comment by GeorgeLeungHK** [comment]
这是在ssh输入命令reboot后的log，看样子跟luci的重启后的log很类似。

Sat Dec 19 18:20:00 2020 cron.err crond[23485]: crond (busybox 1.31.1) started, log level 8
Sat Dec 19 18:20:00 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sat Dec 19 18:20:00 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sat Dec 19 18:20:03 2020 daemon.info dnsmasq[23756]: Connected to system UBus
Sat Dec 19 18:20:04 2020 daemon.info pdnsd[24048]: pdnsd-1.2.9b-par starting.
Sat Dec 19 18:20:05 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sat Dec 19 18:20:05 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sat Dec 19 18:20:08 2020 daemon.info dnsmasq[24612]: Connected to system UBus
Sat Dec 19 18:20:08 2020 cron.err crond[24690]: crond (busybox 1.31.1) started, log level 8
Sat Dec 19 18:20:39 2020 daemon.info procd: - shutdown -
Sat Dec 19 18:20:39 2020 daemon.notice procd: /etc/rc.d/K01AdGuardHome: awk: /etc/config/AdGuardHome.yaml: No such file or directory
Sat Dec 19 18:20:39 2020 daemon.notice procd: /etc/rc.d/K01AdGuardHome: AdGuardHome service disabled
Sat Dec 19 18:20:39 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:20:39 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:20:39 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:20:39 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:20:39 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:20:39 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:20:39 2020 daemon.notice procd: /etc/rc.d/K10baidupcs-web: uci: Entry not found
Sat Dec 19 18:20:39 2020 daemon.notice procd: /etc/rc.d/K10serverchan: serverchan exit ...
Sat Dec 19 18:20:40 2020 cron.err crond[25330]: crond (busybox 1.31.1) started, log level 8
Sat Dec 19 18:20:40 2020 daemon.notice procd: /etc/rc.d/K10xlnetacc: Stop XLNetAcc process PID: 25338
Sat Dec 19 18:20:40 2020 daemon.info udpspeeder[3236]: [0m[32m[2020-12-19 18:20:40][INFO]got sigterm, exit[0m[0m
Sat Dec 19 18:20:40 2020 daemon.info udpspeeder[3237]: [0m[32m[2020-12-19 18:20:40][INFO]got sigterm, exit[0m[0m
Sat Dec 19 18:20:42 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sat Dec 19 18:20:42 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sat Dec 19 18:20:45 2020 daemon.info dnsmasq[25675]: Connected to system UBus
Sat Dec 19 18:20:50 2020 cron.err crond[25789]: crond (busybox 1.31.1) started, log level 8
Sat Dec 19 18:20:50 2020 daemon.notice procd: /etc/rc.d/K15openclash: OpenClash Already Stop
Sat Dec 19 18:20:50 2020 cron.err crond[25935]: crond (busybox 1.31.1) started, log level 8
Sat Dec 19 18:20:50 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sat Dec 19 18:20:50 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sat Dec 19 18:20:53 2020 daemon.info dnsmasq[26034]: Connected to system UBus
Sat Dec 19 18:20:54 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sat Dec 19 18:20:54 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sat Dec 19 18:20:57 2020 daemon.info dnsmasq[26225]: Connected to system UBus
Sat Dec 19 18:20:57 2020 cron.err crond[26260]: crond (busybox 1.31.1) started, log level 8
Sat Dec 19 18:20:57 2020 daemon.notice procd: /etc/rc.d/K15vssr: stop
Sat Dec 19 18:20:58 2020 cron.err crond[26411]: crond (busybox 1.31.1) started, log level 8
Sat Dec 19 18:20:58 2020 authpriv.info dropbear[2764]: Early exit: Terminated by signal
Sat Dec 19 18:20:58 2020 authpriv.info dropbear[10564]: Exit (root) from <192.168.2.217:6475>: Terminated by signal
Sat Dec 19 18:20:58 2020 daemon.notice ttyd[5761]: received signal: SIGTERM (15), exiting...
Sat Dec 19 18:20:58 2020 daemon.notice ttyd[5761]: send ^C to force exit.
Sat Dec 19 18:20:58 2020 kern.warn kernel: [  525.311217] nfsd: last server has exited, flushing export cache
Sat Dec 19 18:20:58 2020 daemon.notice rpc.mountd[5377]: Caught signal 15, un-registering and exiting.

**Comment by GeorgeLeungHK** [comment]
我也尝试过给1219的4GB版本重新上传固件升级，升级后也是卡在重启这块，直到重新插拔电源后才能正常。

**Comment by LewiVir** [comment]
> 我也尝试过给1219的4GB版本重新上传固件升级，升级后也是卡在重启这块，直到重新插拔电源后才能正常。

了解。请明天尝试新的固件，然后反馈一下。
