### ISSUE TITLE
感谢大佬的固件

### ISSUE THREAD

**Issue by bitest** [LewiVir/NanoPi-R4S#33]
看了LewiVir大佬和P3TERX大佬的代码，没有编程基础的我自己摸索了一天，也成功地用Actions编译出了自己的固件（没直接用您的固件是因为我不喜欢插件太多2333）。

话说我按P3TERX大佬的代码能成功修改登录IP的啊？
> sed -i 's/192.168.1.1/192.168.2.1/g' package/base-files/files/bin/config_generate

就是上面这个

还有端口MAC乱跳的问题，我也遇到了，只能等不知道哪位大佬修复了。我的无线网卡驱不动的问题我还在一个个试，毕竟驱动列表里没完全符合我的型号，大佬的1209能驱动也是非常神奇。

**Comment by LewiVir** [comment]
谢谢提醒，之前修改的方式不对。。。
