### ISSUE TITLE
No Internet. May i doing something wrong. please help.

### ISSUE THREAD

**Issue by wikimao** [LewiVir/NanoPi-R4S#6]
i have connected:

Router-->R4S (WAN) 
PC --> R4S ( LAN ) 
 i can login 192.168.2.1, R4S wan configured as DHCP . interface gets IP from router. 

why i don't have internet. is there any special setting?

do you have wechat?

**Comment by LewiVir** [comment]
There are no additional settings for Internet connections. I have tested DCHP/DCHPv6/PPPoE in my network environment, all of them are working normally. I personally do not provide technical support for the firmware.

**Comment by wikimao** [comment]
Got it, thanks.
